### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by andreimarcu** [linx-server/linx-server#266]
If anyone would be interested in taking on this project, I would be willing to transfer it over as development and work on issues has mostly stalled at this point.

Hopefully someone who could dedicate some time to resolving issues at the very least.

Feel free to reply to this issue if interested!

**Comment by ZizzyDizzyMC** [comment]
Well, I've been working on the project in my fork for a bit and while I can safely say I am in no way capable of quality code , I have managed to add some features and fix some small bugs / potential issues I located.
I have looked over the issue queue and at least some of them I know I would be able to help with.

I didn't know if I wanted to respond to this originally but I think I'd be willing to take the plunge if needed.

**Comment by andreimarcu** [comment]
Sounds good to me

**Comment by ZizzyDizzyMC** [comment]
> @ZizzyDizzyMC Will you be added as contributor to this project and merging your work over from your repo? Or should I be cloning your repo?

The short answer is: This repo is the repo you want. 

Longer answer: I was using my repo as a learning tool for `golang` and to add some features - I was going though this repo's issues to fix / add outstanding requests or changes that would be useful for the software and any potential users.

My repo should now be considered stale - the changes I've made will be PR'd into this repo after another day or two of testing, minus the localization I have to undo as my repo is specific to my production file sharing site and not the general linx-server demo site.
